### ISSUE TITLE
Please add files including support.

### ISSUE THREAD

**Issue by yusiwen** [KeyboardFire/i3bang#1]
Thx for your great job! Does it support files including? If not, please add it. 

Because I've got multiple PCs & my laptop running i3wm, each of them have some specific settings, for example, one of my workstation at home have 2 monitors, so the config file for it must have dual-monitor workspaces configurations. And obviously these configs are not needed by others. Now, I'm keeping config files for each computer. If I changed one general config on one of them, I must change every other files.

If there is a way to include config files, then I can move the common part to a 'config.general' file, and specific configs to individual files.

Thx

**Comment by tckmn** [comment]
Another possible solution would be to implement conditionals (ex. `!?<var=foo ... >`  would mean "if var == foo, ...") for environment variables. Thanks, this is definitely something I'll consider adding!

**Comment by tckmn** [comment]
Support for conditionals via environment variables added! Example:

```
!?<USER=someusername
  bindsym ...
  (this is only added to the config file if i3bang was run by user "someusername")
>
```

**Comment by yusiwen** [comment]
Thanks! I'll give it a try ASAP.

**Comment by mmarquezs** [comment]
This works... but it's not useful for me for example since I usually have multiple machines with the  same username. There is anyway to be abale to use other enviroment variables? For example in my case it would be very useful to check the HOST enviroment  variable. I have tried and it doesn't seem to work so I guess it's not supported right now.

**Comment by tckmn** [comment]
@mmarquezs Yes, you should be able to use whichever variable you want...

**Comment by mmarquezs** [comment]
Well... then there is some issue :S  I have this : 

> !?<HOST=morality
>     tray_output eDP1 
> >

And it doesn't work :S but if I use USER works fine :S

And the variable is set, in the terminal I can type echo $HOST and it shows "morality". I use zsh so I checked in bash  and there, HOST is not set but HOSTNAME is , so I tried putting HOSTNAME but same result :S

_EDIT2: By default the var "HOST", "HOSTNAME" is not exported.But USER is exported by default. That's the issue._

_EDIT: I checked your code,.... and well I'm not a ruby programmerbut but I saw you use this ENV[var] to get the variable and used the irb to test and ... HOST or HOSTNAME returns nil... so something I have wrong that makes it not work :S  I will keep checking.. but obviously this is not an issue in your code.._
