### ISSUE TITLE
Raw sections not expanding when referenced

### ISSUE THREAD

**Issue by rexy712** [KeyboardFire/i3bang#12]
I've been converting my config file to utilize your script, but when it comes to making a raw section and then referencing it, nothing happens.

So when I have:

!@<+default_keybindings
bindsym...
>

And then later:

mode "another_mode" {
...
!@default_keybindings
}

The config file will have the `another_mode` section written out literally rather than expanding.
Am I doing something wrong?

**Comment by tckmn** [comment]
Do you have `#!nobracket` in your config file?

**Comment by rexy712** [comment]
Ah, just a stupid error on my part. It works fine now.
