### ISSUE TITLE
 No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by ubuntupunk** [KeyboardFire/i3bang#13]
When I run ./i3bang _config

I get 1: from ./i3bang.rb:259:in `<main>'
./i3bang.rb:259:in `write': No such file or directory @ rb_sysopen - /home/afropunk/.i3/config (Errno::ENOENT)

Using Ubuntu 20.04

**Comment by tckmn** [comment]
You probably have your i3 config file in `~/.config/i3/config` rather than `~/.i3/config`. You can pass the output path as another argument:

    ./i3bang.rb _config config

But you may want to consider using [ppi3](https://github.com/tckmn/ppi3) instead, which I wrote to replace i3bang.

**Comment by ubuntupunk** [comment]
thanks 💎
