### ISSUE TITLE
The color values begin with '#' is ommited in the generated file

### ISSUE THREAD

**Issue by yusiwen** [KeyboardFire/i3bang#2]
I've set a lot of color in my original config file, when using i3bang to generate the new config, these values, which begin with '#', are omitted, causing an i3 reloading error finally.

For example, in _config file, there is:
client.focused #082029 #082029 #cccccc
In the generated config file, it becomes:
client.focused

It seems i3bang.rb treats those values as comments. How can I include some values containing '#'?

Thanks

**Comment by yusiwen** [comment]
I made a Pull Request #3

**Comment by tckmn** [comment]
Thanks for the pull request! This is fixed now.
