### ISSUE TITLE
[feature] Allow specifying output path

### ISSUE THREAD

**Issue by Airblader** [KeyboardFire/i3bang#5]
Not everyone keeps their i3 config in `~/.i3/config`, plus I'd like to temporarily change it for testing purposes.

**Comment by Airblader** [comment]
On the same note, I think the user should be able to specify a full path for both input and output. If I install i3bang into `/usr/bin/i3bang`, I should be able to run `i3bang /home/user/dotfiles/i3/config.bang /home/user/.i3/config`.

Maybe it'd even be appropriate if i3bang were to write the expanded config to stdout if no output file is given.

**Comment by tckmn** [comment]
> I should be able to run `i3bang /home/user/dotfiles/i3/config.bang /home/user/.i3/config`.

Now you can. :D

When not provided, input file defaults to `~/.i3/_config` and output to `~/.i3/config`.

**Comment by Airblader** [comment]
Awesome, thanks!
