### ISSUE TITLE
[question] Expanding variable definitions

### ISSUE THREAD

**Issue by Airblader** [KeyboardFire/i3bang#6]
I'm trying to migrate my config to i3bang, but the syntax isn't very well-specified in the README. Is this some common syntax that I can look up somewhere?

For example, I currently have something like this:

```
set $ws1 "1:foo"
set $ws2 "2:fee"
set $ws3 "3:fii"
```

How do I go about writing this in the i3bang syntax? I tried things like

```
set $ws!!1,2,3 "<1:foo,2:fee,3:fii>"
```

but it didn't come out right. And, in fact, ideally it should be shrunk down to something like

```
set $ws!!1..10 "!!1..10:<foo,fee,fii,.........................>"
```

Is this possible?

**Comment by tckmn** [comment]
Yes, it would be:

```
set $ws!!1..10 "!!<1..10>:!!<foo,fee,fii,...>"
```

**Comment by Airblader** [comment]
OK, thanks, I'll give that a shot. I'd also like to ask about one example in the README, the "Separate expansions" one. What does the `!!1` in `!!1!1..10` stand for?

**Comment by Airblader** [comment]
OK, so I tried

```
set $ws!!1..10 "!!<1..10>:!!<a,b,c,d,e,f,g,h,i,j>"
```

But it gets expanded to

```
set $ws!!1..10 "1:a"
set $ws!!1..10 "2:b"
set $ws!!1..10 "3:c"
set $ws!!1..10 "4:d"
set $ws!!1..10 "5:e"
set $ws!!1..10 "6:f"
set $ws!!1..10 "7:g"
set $ws!!1..10 "8:h"
set $ws!!1..10 "9:i"
set $ws!!1..10 "10:j"
```

In case it's relevant: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]

**Comment by Airblader** [comment]
Looks like adding `#!nobracket` to the bang file works. What exactly does that do?

**Comment by tckmn** [comment]
It allows you to use `!!1..10` instead of `!!<1..10>` when followed by whitespace. (And here's where the disadvantages of being too lazy to write good documentation really start to show... ;) I'll add some more docs when I get the time.)

**Comment by Airblader** [comment]
But shouldn't the above work without that option then?

**Comment by tckmn** [comment]
No, because `!!1..10` is ignored if the option is not set.

**Comment by Airblader** [comment]
Alright, thanks :)
